DROP TABLE "IMPADMIN"."COMPUTENODEINFO";
DROP TABLE "IMPADMIN"."GROUPINFO";
DROP TABLE "IMPADMIN"."HOSTSHAREINSTANCEMAPPINGINFO";
DROP TABLE "IMPADMIN"."INSTANCEINFO";
DROP TABLE "IMPADMIN"."INSTANCESPECINFO";
DROP TABLE "IMPADMIN"."PACKINFO";
DROP TABLE "IMPADMIN"."SERVICEINFO";
DROP TABLE "IMPADMIN"."IMAGE";
DROP TABLE "IMPADMIN"."IMAGELAYERS";
DROP TABLE "IMPADMIN"."IMAGELAYERSMAPPED";
DROP TABLE "IMPADMIN"."NODEIMAGE";
DROP TABLE "IMPADMIN"."REPOSITORY";
DROP TABLE "IMPADMIN"."REPOSITORYSUB";
DROP TABLE "IMPADMIN"."TENANTIMAGE";
DROP TABLE "IMPADMIN"."HOSTINFO";


CREATE TABLE "IMPADMIN"."COMPUTENODEINFO" (
	"COMPUTENODEID" NUMBER,
	"HOSTID" NUMBER,
	"TOTALCPU" NUMBER(9),
	"FREECPU" NUMBER(9),
	"TOTALMEMORY" NUMBER(9),
	"FREEMEMORY" NUMBER(9),
	"TOTALDISK" NUMBER(9),
	"ACCESSNAME" VARCHAR(255),
	"ACCESSAUTH" VARCHAR(2048),
	"CREATEDTIME" TIMESTAMP,
	"UPDATEDTIME" TIMESTAMP
);

CREATE TABLE "IMPADMIN"."GROUPINFO" (
	"GROUPID" NUMBER(19),
	"CREATEDTIME" TIMESTAMP,
	"GROUPDESCRIPTION" VARCHAR(255),
	"GROUPNAME" VARCHAR(255),
	"GROUPTAGS" VARCHAR(255),
	"PROJECTUUID" NUMBER(19),
	"SCRIPT" VARCHAR(10000),
	"STATUS" VARCHAR(255),
	"TENANTUUID" NUMBER(19),
	"UPDATEDTIME" TIMESTAMP,
	"CREATOR" VARCHAR(255),
	"INSTANCECOUNT" NUMBER(10),
	"PACKNAME" VARCHAR(255),
	"PROJECTID" NUMBER(19),
	"TENANTID" NUMBER(19)
);

CREATE TABLE "IMPADMIN"."HOSTSHAREINSTANCEMAPPINGINFO" (
	"HOSTSHAREINSTANCEMAPPINGID" NUMBER,
	"CREATEDTIME" TIMESTAMP,
	"HOSTPATH" VARCHAR(255),
	"HOSTSHAREINSTANCEMAPPINGUUID" VARCHAR(255),
	"INSTANCEID" NUMBER(19),
	"INSTANCEPATH" VARCHAR(255),
	"INSTANCEUUID" VARCHAR(255),
	"UPDATEDTIME" TIMESTAMP,
	"ZFS" NUMBER(10)
);

CREATE TABLE "IMPADMIN"."INSTANCEINFO" (
	"INSTANCEID" NUMBER,
	"TENANTID" NUMBER,
	"PROJECTID" NUMBER,
	"OWNER" VARCHAR(255),
	"INSTANCENAME" VARCHAR(255),
	"INSTANCEDESCRIPTION" VARCHAR(255),
	"INSTANCETAGS" VARCHAR(255),
	"INSTANCETYPE" VARCHAR(255),
	"ENV" VARCHAR(4095),
	"METADATA" VARCHAR(255),
	"HOSTID" NUMBER,
	"IMAGEID" NUMBER,
	"HYPERVISORTYPE" VARCHAR(255),
	"SPECID" NUMBER,
	"CPUS" NUMBER,
	"MEMORY" NUMBER,
	"INSTANCESTATUS" VARCHAR(255),
	"RESULT" VARCHAR(255),
	"RESULTMESSAGE" VARCHAR(600),
	"CREATEDTIME" TIMESTAMP,
	"UPDATEDTIME" TIMESTAMP,
	"AUTOSCALEID" NUMBER,
	"STORAGEGROUPID" NUMBER,
	"STORAGETYPE" NUMBER,
	"TOTALDBSIZE" NUMBER,
	"INSTANCEGROUPID" NUMBER,
	"INTERNALIP" VARCHAR(255),
	"EXTERNALIP" VARCHAR(255),
	"FIPID" NUMBER(9)
);

CREATE TABLE "IMPADMIN"."INSTANCESPECINFO" (
	"SPECID" NUMBER,
	"SPECTYPE" VARCHAR(255),
	"SPECCPU" NUMBER,
	"SPECMEMORY" NUMBER
);

CREATE TABLE "IMPADMIN"."PACKINFO" (
	"PACKAGEID" NUMBER,
	"PACKDESC" VARCHAR(255),
	"PACKNAME" VARCHAR(255),
	"PACKSOURCE" VARCHAR(10000),
	"PACKTYPE" VARCHAR(255),
	"USERNUM" NUMBER(10),
	"PROJECTID" NUMBER(19),
	"TENANTID" NUMBER(19),
	"PACKINFO" VARCHAR(10000),
	"PACKPARA" VARCHAR(10000),
	"TYPE" NUMBER(10)
);

CREATE TABLE "IMPADMIN"."SERVICEINFO" (
	"SVCID" NUMBER,
	"SVCCREATENAME" VARCHAR(255),
	"SVCDELETENAME" VARCHAR(255)
);

CREATE UNIQUE INDEX "IMPADMIN"."IMPADMIN_CON1169500522" ON "IMPADMIN"."PACKINFO" (
	"PACKAGEID" ASC
);

CREATE UNIQUE INDEX "IMPADMIN"."IMPADMIN_CON1174100620" ON "IMPADMIN"."COMPUTENODEINFO" (
	"COMPUTENODEID" ASC
);

CREATE UNIQUE INDEX "IMPADMIN"."INS_PRIM" ON "IMPADMIN"."INSTANCEINFO" (
	"INSTANCEID" ASC
);

CREATE UNIQUE INDEX "IMPADMIN"."PK_SERVICEINFO" ON "IMPADMIN"."SERVICEINFO" (
	"SVCID" ASC
);

CREATE UNIQUE INDEX "IMPADMIN"."SPEC_PRIM" ON "IMPADMIN"."INSTANCESPECINFO" (
	"SPECID" ASC
);


CREATE TABLE "IMPADMIN"."IMAGE" (
	"IMAGEID" NUMBER(15),
	"IMAGEUUID" VARCHAR(32),
	"IMAGENAME" VARCHAR(255),
	"IMAGETAG" VARCHAR(255),
	"IMAGETYPE" VARCHAR(255),
	"IMAGECMD" VARCHAR(1024),
	"NAME" VARCHAR(1024),
	"VALUE" VARCHAR(1024),
	"CREATEDTIME" TIMESTAMP,
	"UPDATEDTIME" TIMESTAMP
);

CREATE TABLE "IMPADMIN"."IMAGELAYERS" (
	"LAYERID" VARCHAR(64),
	"REFCNT" NUMBER(15)
);

CREATE TABLE "IMPADMIN"."IMAGELAYERSMAPPED" (
	"IMAGEID" NUMBER(15),
	"LAYERID" VARCHAR(64),
	"LAYERORDER" NUMBER(15)
);

CREATE TABLE "IMPADMIN"."NODEIMAGE" (
	"NODEIP" VARCHAR(1024),
	"IMAGEID" NUMBER(15),
	"IMAGEUUID" VARCHAR(32),
	"REFCNT" NUMBER
);

CREATE TABLE "IMPADMIN"."REPOSITORY" (
	"IMAGEID" VARCHAR(64),
	"IMAGENAME" VARCHAR(1024),
	"IMAGETAG" VARCHAR(1024),
	"IMAGECMD" VARCHAR(1024),
	"IMAGEENV" VARCHAR(1024)
);

CREATE TABLE "IMPADMIN"."REPOSITORYSUB" (
	"IMAGEID" VARCHAR(64),
	"LAYERID" VARCHAR(64),
	"LAYERORDER" NUMBER
);

CREATE TABLE "IMPADMIN"."TENANTIMAGE" (
	"PROJECTID" VARCHAR(15),
	"TENANTID" VARCHAR(15),
	"IMAGEID" NUMBER(15),
	"IMAGEUUID" VARCHAR(32),
	"IMAGENAME" VARCHAR(255),
	"IMAGETAG" VARCHAR(255),
	"CREATEDTIME" TIMESTAMP,
	"UPDATEDTIME" TIMESTAMP
);

CREATE UNIQUE INDEX "IMPADMIN"."PK_REPOSITORY" ON "IMPADMIN"."REPOSITORY" (
	"IMAGEID" ASC
);

CREATE UNIQUE INDEX "IMPADMIN"."TIBERO_CON44700632" ON "IMPADMIN"."IMAGE" (
	"IMAGEID" ASC
);

CREATE UNIQUE INDEX "IMPADMIN"."TIBERO_CON44900161" ON "IMPADMIN"."IMAGE" (
	"IMAGEUUID" ASC
);

CREATE UNIQUE INDEX "IMPADMIN"."TIBERO_CON45900677" ON "IMPADMIN"."IMAGELAYERS" (
	"LAYERID" ASC
);


CREATE TABLE "IMPADMIN"."HOSTINFO" (
	"HOSTID" NUMBER,
	"HOSTNAME" VARCHAR(255),
	"HOSTTYPE" VARCHAR(255),
	"HYPERVISORTYPE" VARCHAR(255),
	"HOSTIP" VARCHAR(255),
	"CPUARCH" VARCHAR(255),
	"TOTALCPU" NUMBER,
	"TOTALMEMORY" NUMBER,
	"TOTALDISK" NUMBER,
	"AVAILABILITYZONE" VARCHAR(255),
	"STATUS" VARCHAR(255),
	"HOSTPMAC" VARCHAR(255),
	"EXTERNALPORT" VARCHAR(255),
	"INTERNALPORT" VARCHAR(255),
	"SWITCHDPID" NUMBER,
	"SWITCHPORT" NUMBER,
	"ACTIVE" NUMBER,
	"HOSTAGENTNUM" NUMBER,
	"CREATEDTIME" TIMESTAMP,
	"UPDATEDTIME" TIMESTAMP,
	"ACCESSNAME" VARCHAR(255),
	"ACCESSAUTH" VARCHAR(2048),
	"POOLEDDISK" NUMBER
);

CREATE UNIQUE INDEX "IMPADMIN"."HOST_PRIM" ON "IMPADMIN"."HOSTINFO" (
	"HOSTID" ASC
);






ALTER TABLE "IMPADMIN"."HOSTINFO" ADD CONSTRAINT "HOST_PRIM"
PRIMARY KEY (
	"HOSTID"
);

ALTER TABLE "IMPADMIN"."HOSTINFO" MODIFY 	"HOSTNAME" NOT NULL;

ALTER TABLE "IMPADMIN"."HOSTINFO" MODIFY 	"HOSTTYPE" NOT NULL;

ALTER TABLE "IMPADMIN"."HOSTINFO" MODIFY 	"HYPERVISORTYPE" NOT NULL;

ALTER TABLE "IMPADMIN"."HOSTINFO" MODIFY 	"HOSTIP" NOT NULL;

ALTER TABLE "IMPADMIN"."HOSTINFO" MODIFY 	"CPUARCH" NOT NULL;

ALTER TABLE "IMPADMIN"."HOSTINFO" MODIFY 	"TOTALCPU" NOT NULL;

ALTER TABLE "IMPADMIN"."HOSTINFO" MODIFY 	"TOTALMEMORY" NOT NULL;

ALTER TABLE "IMPADMIN"."HOSTINFO" MODIFY 	"TOTALDISK" NOT NULL;

ALTER TABLE "IMPADMIN"."HOSTINFO" MODIFY 	"STATUS" NOT NULL;

ALTER TABLE "IMPADMIN"."HOSTINFO" MODIFY 	"HOSTPMAC" NOT NULL;

ALTER TABLE "IMPADMIN"."HOSTINFO" MODIFY 	"EXTERNALPORT" NOT NULL;

ALTER TABLE "IMPADMIN"."HOSTINFO" MODIFY 	"INTERNALPORT" NOT NULL;

ALTER TABLE "IMPADMIN"."HOSTINFO" MODIFY 	"SWITCHDPID" NOT NULL;

ALTER TABLE "IMPADMIN"."HOSTINFO" MODIFY 	"SWITCHPORT" NOT NULL;

ALTER TABLE "IMPADMIN"."HOSTINFO" MODIFY 	"ACTIVE" NOT NULL;

ALTER TABLE "IMPADMIN"."HOSTINFO" MODIFY 	"HOSTAGENTNUM" NOT NULL;

ALTER TABLE "IMPADMIN"."HOSTINFO" MODIFY 	"CREATEDTIME" NOT NULL;

ALTER TABLE "IMPADMIN"."HOSTINFO" MODIFY 	"UPDATEDTIME" NOT NULL;



